/* ============================================================
   Baza pytan - egzamin dyplomowy, Informatyka (PL)
   Zakres: zagadnienia ogolne z listy dyplomowej (PDF) — 5 dzialow.
   Fiszka:  { id, topic, q, a }
   Quiz:    { id, topic, q, options:[4], correct:<indeks 0..3>, explain }
   topic musi pasowac do id z TOPICS. Edytuj swobodnie.
   ============================================================ */

const TOPICS = [
  {"id":"arch","code":"ARCH","name":"Architektura komputerów i systemy operacyjne"},
  {"id":"netbasics","code":"NETB","name":"Sieci komputerowe (podstawy)"},
  {"id":"dsp","code":"DSP","name":"Sygnały, multimedia i matematyka"},
  {"id":"elec","code":"ELE","name":"Elektronika"},
  {"id":"prog","code":"PROG","name":"Programowanie (podstawy)"}
];

const DECK = [
  {"id":"arch1","topic":"arch","q":"Magistrala (szyna) systemowa — elementy składowe.","a":"Magistrala systemowa łączy procesor, pamięć i urządzenia we/wy. Składa się z trzech magistral: adresowej (przesyła adresy komórek pamięci/urządzeń, zwykle jednokierunkowa), danych (przesyła właściwe dane, dwukierunkowa) i sterującej (sygnały kontrolne: odczyt/zapis, zegar, przerwania, gotowość). Szerokość magistrali danych i adresowej wpływa na wydajność i adresowalną pamięć."},
  {"id":"arch2","topic":"arch","q":"Założenia maszyny von Neumanna.","a":"Wspólna pamięć dla danych i programu (program przechowywany), sekwencyjne pobieranie i wykonywanie instrukcji, jednostka centralna z ALU i jednostką sterującą, pamięć, urządzenia we/wy oraz wspólna magistrala. Cechą jest wąskie gardło von Neumanna (jedna magistrala dla danych i instrukcji). Alternatywa: architektura harwardzka (oddzielne pamięci/magistrale)."},
  {"id":"arch3","topic":"arch","q":"Proces i wątek — różnice.","a":"Proces to wykonujący się program z własną przestrzenią adresową i zasobami; jest izolowany od innych procesów. Wątek to jednostka wykonania wewnątrz procesu, współdzieląca jego pamięć i zasoby. Wątki są lżejsze, szybciej się przełączają i komunikują (wspólna pamięć), ale wymagają synchronizacji; procesy są bezpieczniejsze przez izolację."},
  {"id":"arch4","topic":"arch","q":"Podstawowe metody komunikacji między procesami (IPC).","a":"Pamięć współdzielona (shared memory — najszybsza), kolejki komunikatów (message queues), potoki (pipes, named pipes), gniazda (sockets — także sieciowe), sygnały, semafory i muteksy do synchronizacji, pliki. Wybór zależy od izolacji, wydajności i tego, czy procesy są na jednej maszynie."},
  {"id":"arch5","topic":"arch","q":"Pojęcie systemu operacyjnego.","a":"Oprogramowanie zarządzające zasobami sprzętowymi i pośredniczące między sprzętem a aplikacjami. Zadania: zarządzanie procesami (szeregowanie), pamięcią, systemem plików, urządzeniami we/wy oraz bezpieczeństwem i dostępem. Udostępnia interfejs programistyczny (API, wywołania systemowe) i użytkownika (powłoka, GUI). Przykłady: Windows, Linux, macOS."},
  {"id":"arch6","topic":"arch","q":"Rodzaje pamięci systemów komputerowych.","a":"Hierarchia wg szybkości i pojemności: rejestry procesora (najszybsze), pamięć podręczna cache (L1/L2/L3), pamięć operacyjna RAM (ulotna, robocza), pamięć masowa (SSD/HDD — trwała, duża), pamięć ROM/Flash (nieulotna, np. firmware). Im bliżej procesora, tym szybsza, mniejsza i droższa — to kompromis szybkość/pojemność/koszt."},
  {"id":"arch7","topic":"arch","q":"Architektura komputerów — co opisuje.","a":"Organizacja i zasada działania komputera: procesor (ALU, jednostka sterująca, rejestry), pamięć, układy we/wy i magistrale. Obejmuje listę rozkazów, tryby adresowania, potokowość (pipelining). Modele: von Neumanna i harwardzka; filozofie listy rozkazów: CISC i RISC."},
  {"id":"arch8","topic":"arch","q":"System operacyjny czasu rzeczywistego (RTOS).","a":"Zapewnia deterministyczny, przewidywalny czas reakcji na zdarzenia w określonych ramach czasowych. Twardy RTOS — przekroczenie terminu oznacza awarię (ABS, sterowanie przemysłowe); miękki — dopuszcza sporadyczne opóźnienia (multimedia). Cechy: szeregowanie priorytetowe z wywłaszczaniem, niskie i przewidywalne opóźnienia."},
  {"id":"arch9","topic":"arch","q":"RAID — rodzaje.","a":"Technologia łączenia dysków dla wydajności i/lub niezawodności. RAID 0 (striping — wydajność, brak redundancji), RAID 1 (mirroring — kopia lustrzana), RAID 5 (striping + rozproszona parzystość, odporność na utratę 1 dysku), RAID 6 (podwójna parzystość, odporność na 2 dyski), RAID 10 (1+0 — lustro + striping, wydajność i bezpieczeństwo)."},
  {"id":"nb1","topic":"netbasics","q":"Model OSI.","a":"Model odniesienia o 7 warstwach: fizyczna, łącza danych, sieciowa, transportowa, sesji, prezentacji, aplikacji. Każda warstwa świadczy usługi warstwie wyższej i korzysta z niższej, co standaryzuje i porządkuje komunikację sieciową. Model TCP/IP jest jego uproszczeniem (4 warstwy)."},
  {"id":"nb2","topic":"netbasics","q":"IPv4 a IPv6 — różnice.","a":"IPv4 — adres 32-bitowy (ok. 4,3 mld adresów), zapis dziesiętny z kropkami, wyczerpana pula, powszechny NAT. IPv6 — adres 128-bitowy (ogromna pula), zapis szesnastkowy z dwukropkami, autokonfiguracja (SLAAC), wbudowane wsparcie IPsec, brak broadcastu (multicast/anycast), uproszczony nagłówek."},
  {"id":"nb3","topic":"netbasics","q":"Klasy adresów IP — organizacja adresów.","a":"Klasowy podział IPv4: klasa A (0–127, duże sieci), B (128–191, średnie), C (192–223, małe), D (224–239, multicast), E (240–255, eksperymentalna). Adres dzieli się na część sieci i hosta. Współcześnie klasy zastąpiono adresowaniem bezklasowym CIDR (maski o dowolnej długości, np. /24)."},
  {"id":"nb4","topic":"netbasics","q":"Kontrola zasięgu pakietów IP (TTL).","a":"Pole TTL (Time To Live) w nagłówku IP to licznik zmniejszany o 1 przez każdy router na trasie. Gdy osiągnie 0, pakiet jest odrzucany, a nadawca dostaje komunikat ICMP (Time Exceeded). Zapobiega to krążeniu pakietów w pętli w nieskończoność; mechanizm wykorzystuje narzędzie traceroute."},
  {"id":"nb5","topic":"netbasics","q":"Sterowanie prędkością transmisji w protokole TCP.","a":"TCP stosuje kontrolę przepływu (okno przesuwne — by nie zalać wolniejszego odbiorcy) i kontrolę przeciążenia sieci: slow start (wykładniczy wzrost okna), congestion avoidance (wzrost liniowy), fast retransmit i fast recovery. Okno rośnie przy potwierdzeniach (ACK), a maleje przy stratach pakietów."},
  {"id":"nb6","topic":"netbasics","q":"Sposoby przesyłania informacji między dwoma punktami.","a":"Kierunkowość: simpleks (jednokierunkowo), półdupleks (naprzemiennie w obu kierunkach), pełny dupleks (jednocześnie w obu). Sposób: transmisja szeregowa vs równoległa. Sposób zestawienia: komutacja łączy (circuit switching — dedykowana ścieżka) i komutacja pakietów (packet switching — dane w pakietach)."},
  {"id":"nb7","topic":"netbasics","q":"Sieci bezprzewodowe — wady i zalety.","a":"Zalety: mobilność, łatwa i tania instalacja (brak okablowania), skalowalność, dostęp w trudnych miejscach. Wady: mniejsze bezpieczeństwo (łatwy podsłuch), zakłócenia i tłumienie sygnału, mniejsza i zmienna przepustowość, zależność od zasięgu i przeszkód, współdzielone medium (kolizje, spadek wydajności)."},
  {"id":"nb8","topic":"netbasics","q":"Translacja adresów w sieciach IP (NAT).","a":"NAT (Network Address Translation) tłumaczy prywatne adresy IP sieci lokalnej na publiczny adres (i odwrotnie) na routerze brzegowym. Oszczędza pulę publicznych adresów IPv4 i ukrywa wewnętrzną strukturę sieci (dodatkowa warstwa ochrony). Tablica translacji wiąże połączenia wewnętrzne z zewnętrznymi."},
  {"id":"nb9","topic":"netbasics","q":"Porównanie NAT i PAT.","a":"NAT mapuje adresy IP (np. 1:1 lub z puli adresów). PAT (Port Address Translation, zwany NAT overload) mapuje wiele adresów prywatnych na jeden publiczny, rozróżniając poszczególne połączenia po numerach portów. PAT jest najczęściej spotykany w domowych routerach (wiele urządzeń, jeden publiczny IP)."},
  {"id":"nb10","topic":"netbasics","q":"Switch a router — różnice.","a":"Przełącznik (switch) działa w warstwie 2 (łącza danych) i przełącza ramki w obrębie jednej sieci LAN na podstawie adresów MAC. Router działa w warstwie 3 (sieciowej) i trasuje pakiety między różnymi sieciami na podstawie adresów IP i tablicy routingu. Switch buduje sieć lokalną, router łączy sieci."},
  {"id":"nb11","topic":"netbasics","q":"Protokoły i usługi sieciowe.","a":"Protokoły określają reguły komunikacji: HTTP/HTTPS, FTP, SMTP/IMAP/POP3, DNS, DHCP, TCP, UDP, IP, ICMP, ARP. Usługi realizują funkcje dla użytkownika: serwer WWW, poczta, DNS (zamiana nazw na adresy IP), DHCP (automatyczny przydział adresów), udostępnianie plików. Protokół to zasady, usługa to świadczona funkcja."},
  {"id":"nb12","topic":"netbasics","q":"Enkapsulacja.","a":"Proces zagnieżdżania danych w nagłówki kolejnych warstw przy schodzeniu w dół stosu protokołów: dane aplikacji to segment TCP, to pakiet IP, to ramka Ethernet (z adresami MAC). Każda warstwa dodaje swój nagłówek (tworząc PDU). U odbiorcy następuje odwrotny proces — dekapsulacja."},
  {"id":"nb13","topic":"netbasics","q":"Multicasting.","a":"Rozsyłanie grupowe — jeden nadawca wysyła pakiet jednocześnie do grupy zainteresowanych odbiorców, efektywnie wykorzystując pasmo (w odróżnieniu od unicastu 1:1 i broadcastu do wszystkich). Wykorzystuje adresy klasy D i protokół IGMP do zarządzania grupami. Zastosowania: streaming, IPTV, wideokonferencje."},
  {"id":"nb14","topic":"netbasics","q":"Technologia VoIP.","a":"Voice over IP — przesyłanie głosu w postaci pakietów danych przez sieć IP zamiast tradycyjnej telefonii komutowanej. Wykorzystuje protokoły sygnalizacyjne (SIP, H.323) i transmisji w czasie rzeczywistym (RTP) oraz kodeki głosu. Zalety: niższy koszt, integracja usług; wyzwania: opóźnienia, jitter, zapewnienie QoS."},
  {"id":"nb15","topic":"netbasics","q":"Usługi w sieciach ATM i ich przeznaczenie.","a":"ATM (Asynchronous Transfer Mode) przesyła dane w komórkach o stałym rozmiarze 53 bajtów i oferuje klasy usług z gwarancją jakości (QoS): CBR (stała przepływność — głos, wideo), VBR (zmienna), ABR (dostępna, z informacją zwrotną), UBR (bez gwarancji — dane). Pozwala integrować ruch o różnych wymaganiach."},
  {"id":"nb16","topic":"netbasics","q":"Struktura sieci GSM.","a":"Stacja ruchoma (MS z kartą SIM); podsystem stacji bazowych BSS — BTS (nadajnik-odbiornik w komórce) i BSC (kontroler stacji bazowych); podsystem sieciowy NSS — MSC (centrala komutacyjna), rejestry abonentów HLR i VLR oraz centrum uwierzytelniania AuC. Obszar dzieli się na komórki obsługiwane przez BTS."},
  {"id":"dsp1","topic":"dsp","q":"Metody analizy sygnałów (głównie częstotliwościowe).","a":"Analiza częstotliwościowa przenosi sygnał z dziedziny czasu do dziedziny częstotliwości, ujawniając jego widmo. Narzędzia: transformata Fouriera (FT), dyskretna DFT i szybka FFT, analiza widmowa, transformata Z, krótkoczasowa STFT i transformata falkowa (wavelet) dla sygnałów niestacjonarnych."},
  {"id":"dsp2","topic":"dsp","q":"Twierdzenie o próbkowaniu (Nyquista-Shannona).","a":"Aby wiernie odtworzyć sygnał analogowy z jego próbek, częstotliwość próbkowania musi być co najmniej dwa razy większa od najwyższej częstotliwości w sygnale: fs >= 2·fmax. Niespełnienie warunku powoduje aliasing (nakładanie się widm i zniekształcenia). Połowa częstotliwości próbkowania to częstotliwość Nyquista."},
  {"id":"dsp3","topic":"dsp","q":"Kompresja stratna i bezstratna.","a":"Bezstratna odtwarza oryginał dokładnie (ZIP, PNG, FLAC; metody RLE, Huffman, LZ77) — mniejszy stopień kompresji. Stratna usuwa część informacji (mało istotnej percepcyjnie) dla znacznie większej kompresji (JPEG, MP3, MPEG) i jest nieodwracalna. To kompromis między rozmiarem a jakością."},
  {"id":"dsp4","topic":"dsp","q":"Kodeki.","a":"Kodek (koder-dekoder) to algorytm/program kompresujący i dekompresujący dane audio lub wideo na potrzeby transmisji i przechowywania. Określa format, stopień kompresji i jakość. Przykłady wideo: H.264, H.265 (HEVC), VP9, AV1; audio: MP3, AAC, Opus, FLAC."},
  {"id":"dsp5","topic":"dsp","q":"Kodowanie JPEG.","a":"Stratna kompresja obrazu: konwersja RGB do przestrzeni YCbCr i podpróbkowanie chrominancji (oko mniej czułe na kolor), podział na bloki 8x8, dyskretna transformata kosinusowa (DCT), kwantyzacja współczynników (główne źródło strat), a następnie kodowanie entropijne (RLE i Huffmana)."},
  {"id":"dsp6","topic":"dsp","q":"Filtry — pasmo i częstotliwości charakterystyczne.","a":"Rodzaje wg pasma przepuszczania: dolnoprzepustowy (LP), górnoprzepustowy (HP), pasmowoprzepustowy (BP), pasmowozaporowy (BS). Częstotliwość graniczna (cutoff) wyznacza się zwykle przy spadku o 3 dB. Filtry opisują charakterystyka amplitudowa i fazowa; realizacja analogowa lub cyfrowa (FIR/IIR)."},
  {"id":"dsp7","topic":"dsp","q":"Transmitancja.","a":"Transmitancja (funkcja przejścia) to stosunek transformaty Laplace'a sygnału wyjściowego do wejściowego przy zerowych warunkach początkowych: H(s) = Y(s)/X(s). Opisuje zachowanie liniowego układu — jego bieguny i zera, stabilność oraz charakterystyki częstotliwościowe."},
  {"id":"dsp8","topic":"dsp","q":"Aproksymacja i interpolacja — różnica.","a":"Interpolacja wyznacza wartości funkcji w punktach pośrednich tak, by krzywa przechodziła dokładnie przez wszystkie znane punkty (np. wielomianowa, splajny). Aproksymacja dopasowuje funkcję przybliżającą dane, niekoniecznie przez punkty, minimalizując błąd (np. metoda najmniejszych kwadratów) — lepsza przy danych zaszumionych."},
  {"id":"dsp9","topic":"dsp","q":"Różniczkowanie i całkowanie.","a":"Różniczkowanie wyznacza tempo zmian funkcji (pochodną); całkowanie wyznacza pole pod krzywą i jest operacją odwrotną do różniczkowania. W przetwarzaniu sygnałów różniczkowanie uwypukla szybkie zmiany (krawędzie), a całkowanie wygładza i sumuje. Numerycznie: różnice skończone, metoda trapezów, metoda Simpsona."},
  {"id":"dsp10","topic":"dsp","q":"Definicja pochodnej.","a":"Pochodna funkcji f w punkcie x to granica ilorazu różnicowego: f'(x) = lim (h dążącego do 0) z [f(x+h) - f(x)] / h. Geometrycznie jest to nachylenie stycznej do wykresu w danym punkcie, a fizycznie — chwilowa szybkość zmian wielkości."},
  {"id":"dsp11","topic":"dsp","q":"Wartość średnia i chwilowa.","a":"Wartość chwilowa to wartość sygnału w danej chwili t. Wartość średnia to wartość uśredniona w okresie/przedziale (składowa stała); dla czystej sinusoidy za okres wynosi 0. Dla sygnałów zmiennych istotna jest też wartość skuteczna (RMS), np. dla sinusoidy równa amplitudzie podzielonej przez pierwiastek z 2."},
  {"id":"dsp12","topic":"dsp","q":"Wektory i macierze.","a":"Wektor to uporządkowany ciąg liczb (wiersz lub kolumna); macierz to prostokątna tablica liczb. Operacje: dodawanie, mnożenie przez skalar, mnożenie macierzy, transpozycja, wyznacznik, macierz odwrotna. Zastosowania: rozwiązywanie układów równań, przekształcenia liniowe, grafika komputerowa, uczenie maszynowe."},
  {"id":"dsp13","topic":"dsp","q":"Odchylenie standardowe.","a":"Miara rozproszenia danych wokół wartości średniej — pierwiastek kwadratowy z wariancji (średniej kwadratów odchyleń od średniej). Im większe, tym dane są bardziej rozproszone. W rozkładzie normalnym około 68% wartości mieści się w przedziale plus/minus jedno odchylenie standardowe od średniej."},
  {"id":"dsp14","topic":"dsp","q":"Wzmocnienie i jednostka mocy (decybel).","a":"Wzmocnienie to stosunek sygnału wyjściowego do wejściowego. Wyraża się w decybelach (dB) — skala logarytmiczna: dla mocy 10·log10(Pwy/Pwe), dla napięcia 20·log10(Uwy/Uwe). Wzrost o 3 dB oznacza około podwojenie mocy. Moc mierzy się w watach (W); dBm odnosi się do 1 mW."},
  {"id":"dsp15","topic":"dsp","q":"Porównanie fali świetlnej z falą elektromagnetyczną.","a":"Światło jest falą elektromagnetyczną — szczególnym przypadkiem w zakresie widzialnym (ok. 380–750 nm). Wszystkie fale EM rozchodzą się w próżni z prędkością c i mają wzajemnie prostopadłe pola elektryczne i magnetyczne, prostopadłe do kierunku ruchu. Różni je zakres częstotliwości/długości fali: widmo EM obejmuje fale radiowe, mikrofale, podczerwień, światło widzialne, ultrafiolet, promieniowanie X i gamma."},
  {"id":"elec1","topic":"elec","q":"Zasada działania tranzystora.","a":"Tranzystor to półprzewodnikowy element sterujący przepływem prądu. Bipolarny (BJT): mały prąd bazy steruje znacznie większym prądem między kolektorem a emiterem (efekt wzmacniania). Unipolarny (FET/MOSFET): napięcie na bramce steruje przewodnością kanału. Tranzystor pełni funkcję wzmacniacza sygnału lub przełącznika (klucza) w układach cyfrowych."},
  {"id":"elec2","topic":"elec","q":"Elementy półprzewodnikowe.","a":"Bazują na półprzewodnikach (krzem, german) domieszkowanych do typu n i p; działanie opiera się na złączu p-n i sterowaniu nośnikami ładunku. Należą do nich: dioda (przewodzi w jednym kierunku), tranzystor, tyrystor, dioda LED, fotodioda oraz układy scalone integrujące wiele takich elementów."},
  {"id":"elec3","topic":"elec","q":"Wzmacniacz operacyjny — parametry.","a":"Wzmacniacz różnicowy o bardzo dużym wzmocnieniu, zwykle pracujący ze sprzężeniem zwrotnym. Ważne parametry: bardzo duże wzmocnienie otwartej pętli, duża impedancja wejściowa, mała impedancja wyjściowa, pasmo (iloczyn wzmocnienie-pasmo GBW), napięcie niezrównoważenia (offset), współczynnik tłumienia sygnału wspólnego (CMRR) oraz szybkość narastania (slew rate)."},
  {"id":"elec4","topic":"elec","q":"Przerzutniki.","a":"Podstawowe elementy pamiętające w technice cyfrowej, przechowujące 1 bit. Rodzaje: RS (SR), D (zatrzaskuje wartość wejścia), JK (uniwersalny), T (zliczający, zmienia stan). Zatrzaski (latch) są poziomowe/asynchroniczne, a przerzutniki taktowane (flip-flop) reagują na zbocze zegara. Budują rejestry, liczniki i pamięci."},
  {"id":"prog1","topic":"prog","q":"Programowanie sekwencyjne i strukturalne.","a":"Sekwencyjne — instrukcje wykonywane kolejno, jedna po drugiej. Strukturalne — program budowany z trzech podstawowych struktur sterowania: sekwencji, wyboru (warunek) i iteracji (pętla), z podziałem na podprogramy (funkcje, procedury) i bez instrukcji skoku goto. Poprawia czytelność, testowanie i utrzymanie kodu."},
  {"id":"prog2","topic":"prog","q":"Programowanie obiektowe — konstruktor i destruktor.","a":"Konstruktor to specjalna metoda wywoływana przy tworzeniu obiektu — inicjalizuje jego stan (atrybuty) i może alokować zasoby. Destruktor jest wywoływany przy niszczeniu obiektu i zwalnia zasoby (pamięć, pliki, połączenia). W językach z automatycznym odśmiecaniem pamięci (Java, Python) sprzątanie realizują mechanizmy GC i metody specjalne (finalizatory, __del__)."},
  {"id":"prog3","topic":"prog","q":"Przekazanie parametrów do procedury.","a":"Przez wartość — przekazywana jest kopia argumentu, więc zmiany wewnątrz procedury nie wpływają na oryginał. Przez referencję/wskaźnik — przekazywany jest dostęp do oryginału, więc zmiany są widoczne na zewnątrz. Istnieje też przekazywanie przez nazwę. Wybór wpływa na efekty uboczne i wydajność (kopiowanie dużych struktur)."},
  {"id":"prog4","topic":"prog","q":"Algorytm a kod programu.","a":"Algorytm to skończony, jednoznaczny ciąg kroków rozwiązujący problem, niezależny od języka programowania (zapis np. w pseudokodzie lub schemacie blokowym). Kod programu to konkretna implementacja algorytmu w wybranym języku, wykonywalna przez komputer. W skrócie: algorytm to metoda/pomysł, kod to jego realizacja."}
];

const QUIZ = [
  {"id":"qarch1","topic":"arch","q":"Magistrala systemowa dzieli się na:","options":["wejściową i wyjściową","adresową, danych i sterującą","wewnętrzną i zewnętrzną","cyfrową i analogową"],"correct":1,"explain":"Trzy magistrale: adresowa, danych, sterująca."},
  {"id":"qarch2","topic":"arch","q":"Cechą maszyny von Neumanna jest:","options":["oddzielna pamięć danych i programu","wspólna pamięć dla danych i programu","brak procesora","brak pamięci"],"correct":1,"explain":"Von Neumann: program przechowywany we wspólnej pamięci z danymi."},
  {"id":"qarch3","topic":"arch","q":"RAID 1 to:","options":["striping bez redundancji","mirroring (kopia lustrzana)","parzystość rozproszona","podwójna parzystość"],"correct":1,"explain":"RAID 1 to mirroring — lustrzana kopia danych."},
  {"id":"qarch4","topic":"arch","q":"Wątki w obrębie jednego procesu:","options":["mają osobne przestrzenie adresowe","współdzielą pamięć procesu","nie mogą działać równolegle","są cięższe niż procesy"],"correct":1,"explain":"Wątki współdzielą pamięć i zasoby procesu (wymagają synchronizacji)."},
  {"id":"qnb1","topic":"netbasics","q":"Model OSI ma liczbę warstw:","options":["4","5","7","9"],"correct":2,"explain":"Model OSI ma 7 warstw (TCP/IP — 4)."},
  {"id":"qnb2","topic":"netbasics","q":"Pole TTL w pakiecie IP służy do:","options":["szyfrowania","ograniczenia czasu życia/pętli pakietu","adresowania MAC","kompresji"],"correct":1,"explain":"TTL maleje na każdym routerze; przy 0 pakiet jest odrzucany."},
  {"id":"qnb3","topic":"netbasics","q":"Switch działa w warstwie, a router w warstwie:","options":["3 i 2","2 (MAC) i 3 (IP)","1 i 2","4 i 3"],"correct":1,"explain":"Switch — warstwa 2 (MAC), router — warstwa 3 (IP)."},
  {"id":"qnb4","topic":"netbasics","q":"PAT (NAT overload) rozróżnia połączenia po:","options":["adresach MAC","numerach portów","numerach VLAN","TTL"],"correct":1,"explain":"PAT mapuje wiele adresów na jeden publiczny, rozróżniając je portami."},
  {"id":"qnb5","topic":"netbasics","q":"Komórka ATM ma stały rozmiar:","options":["48 bajtów","53 bajty","64 bajty","128 bajtów"],"correct":1,"explain":"ATM używa komórek 53 B (48 B danych + 5 B nagłówka)."},
  {"id":"qdsp1","topic":"dsp","q":"Twierdzenie o próbkowaniu wymaga, by fs było:","options":["równe fmax","co najmniej 2·fmax","mniejsze niż fmax","równe zeru"],"correct":1,"explain":"Nyquist: fs >= 2·fmax, inaczej aliasing."},
  {"id":"qdsp2","topic":"dsp","q":"Kodowanie JPEG wykorzystuje przekształcenie:","options":["FFT","DCT (dyskretna transformata kosinusowa)","transformatę Laplace'a","RLE jako jedyny krok"],"correct":1,"explain":"JPEG: bloki 8x8, DCT, kwantyzacja, kodowanie entropijne."},
  {"id":"qdsp3","topic":"dsp","q":"Kompresja bezstratna to np.:","options":["JPEG","MP3","PNG / FLAC","MPEG"],"correct":2,"explain":"Bezstratne: PNG, FLAC, ZIP; stratne: JPEG, MP3, MPEG."},
  {"id":"qdsp4","topic":"dsp","q":"Wzrost mocy o 3 dB oznacza w przybliżeniu:","options":["spadek o połowę","podwojenie mocy","brak zmiany","10-krotny wzrost"],"correct":1,"explain":"+3 dB to około podwojenie mocy (skala logarytmiczna)."},
  {"id":"qdsp5","topic":"dsp","q":"Odchylenie standardowe to:","options":["średnia wartości","pierwiastek z wariancji (rozproszenie)","wartość maksymalna","mediana"],"correct":1,"explain":"Odchylenie standardowe = pierwiastek z wariancji."},
  {"id":"qelec1","topic":"elec","q":"W tranzystorze bipolarnym (BJT) prądem sterującym jest:","options":["prąd kolektora","prąd bazy","napięcie bramki","prąd emitera ujemny"],"correct":1,"explain":"W BJT mały prąd bazy steruje dużym prądem kolektor-emiter."},
  {"id":"qelec2","topic":"elec","q":"Dioda przewodzi prąd:","options":["w obu kierunkach","w jednym kierunku","tylko zmienny","tylko przy zerowym napięciu"],"correct":1,"explain":"Dioda (złącze p-n) przewodzi zasadniczo w jednym kierunku."},
  {"id":"qelec3","topic":"elec","q":"Slew rate wzmacniacza operacyjnego to:","options":["wzmocnienie napięciowe","szybkość narastania sygnału wyjściowego","impedancja wejściowa","napięcie offsetu"],"correct":1,"explain":"Slew rate określa maksymalną szybkość zmian napięcia wyjściowego."},
  {"id":"qprog1","topic":"prog","q":"Programowanie strukturalne opiera się na strukturach:","options":["dziedziczenie, polimorfizm, hermetyzacja","sekwencja, wybór, iteracja","goto i skoki","wyłącznie rekurencja"],"correct":1,"explain":"Strukturalne: sekwencja, wybór (warunek), iteracja (pętla)."},
  {"id":"qprog2","topic":"prog","q":"Przekazanie parametru przez wartość oznacza, że:","options":["zmiany w procedurze zmieniają oryginał","procedura dostaje kopię, oryginał bez zmian","parametr jest globalny","parametr jest wskaźnikiem"],"correct":1,"explain":"Przez wartość: kopia argumentu, oryginał pozostaje niezmieniony."},
  {"id":"qprog3","topic":"prog","q":"Algorytm w odróżnieniu od kodu programu jest:","options":["zależny od języka","niezależny od języka (metoda rozwiązania)","wykonywalny przez CPU","zawsze w C++"],"correct":1,"explain":"Algorytm to metoda niezależna od języka; kod to jej implementacja."}
];
